# A container with post start hook
---
apiVersion: v1
kind: Pod
metadata:
  name: post-start-hook
spec:
  containers:
  - image: some-image
    name: main
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/postStart.sh
