# A container with a pre stop hook
---
apiVersion: v1
kind: Pod
metadata:
  name: pre-stop-hook
spec:
  containers:
  - image: some-image
    name: main
    lifecycle:
      preStop:
        httpGet:
          port: 8080
          path: shutdown
