# DeploymentConfig for starting up the random-generator-runtime
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-generator
  template:
    metadata:
      labels:
        app: random-generator
    spec:
      containers:
      - image: k8spatterns/random-generator
        imagePullPolicy: Always
        name: random-generator
        ports:
        - containerPort: 8080
          protocol: TCP
---
# A service for exposing our random generator
apiVersion: v1
kind: Service
metadata:
  name: random-generator
spec:
  selector:
    app: random-generator
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort
