---
# Integration object which described a full integration including
# references to connections and contains the steps to perform
# for the integration
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: integrations.syndesis.io
spec:
  scope: Namespaced
  group: syndesis.io
  version: v1
  names:
    kind: Integration
    singular: integration
    plural: integrations
---
# A connection is an integration endpoint put also can be used in the middle
# of an integration
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: connections.syndesis.io
spec:
  scope: Namespaced
  group: syndesis.io
  version: v1
  names:
    kind: Connection
    singular: connection
    plural: connections
